### ISSUE TITLE
Quote added when i add List object in 

### ISSUE THREAD

**Issue by NerioJG** [Leksat/dart-exportable#10]
Hello Leksat,

I have a weird behavior when i use your lib to serialize an object;
______________________________________________
    Condition t = new Condition();

    Configurator configurator1 = new Configurator();
    configurator1.alias = conf_b_1;
    configurator1.value = conf1;

    Configurator configurator2 = new Configurator();
    configurator2.alias = conf_b_2;
    configurator2.value = conf2;

    t.configurators.add(configurator1);
    t.configurators.add(configurator2);

    print(t.toJson()); //!\\ here is the problem.
______________________________________________
Here the result:
print configurator1 :   {"alias":"1","value":"10"}
print configurator2 :   {"alias":"1","value":"10"}

It seems good. 

But when i print the entire object t:

{"ref":"1","logicalRefId":"10","value":"10","alias":false,"configurators":["{\"alias\":\"1\",\"value\":\"10\"}","{\"alias\":\"1\",\"value\":\"10\"}"]}

Quote are added around the two configurator objects. Why ? 
Is this a bug or a misuse  of the lib ?

Thx in advance,
Nerio

**Comment by Leksat** [comment]
I did not work on dart-exportable since 2013.
You better to check https://www.dartlang.org/articles/serialization/ for a recommended serialization libs.
